name: Destroy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to destroy'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

env:
  TF_VER: 1.5.7

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate terraform.tfvars
        run: |
          cat <<EOF > envs/dev/terraform.tfvars
          aws_region             = "${{ secrets.TF_aws_region }}"
          project_name           = "${{ secrets.TF_project_name }}"
          environment            = "dev"
          cloudfront_price_class = "${{ secrets.TF_cloudfront_price_class }}"
          table_name             = "${{ vars.TABLE_NAME }}"
          hash_key               = "${{ vars.HASH_KEY }}"
          attributes             = ${{ vars.ATTRIBUTES }}
          ttl_attribute_name     = "${{ vars.TTL_ATTRIBUTE_NAME }}"
          ttl_enabled            = ${{ vars.TTL_ENABLED }}
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VER }}

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions

      - name: Cleanup previous state
        run: rm -rf envs/${{ github.event.inputs.environment }}/.terraform

      - name: Terraform Init
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve
