name: Destroy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to destroy'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

env:
  TF_VER: 1.5.7

jobs:
  destroy:
    name: Destroy (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate terraform.tfvars
        run: |
          cat > envs/${{ github.event.inputs.environment }}/terraform.tfvars <<EOF
          aws_region             = "${{ secrets.TF_aws_region }}"
          project_name           = "${{ secrets.TF_project_name }}"
          environment            = "${{ github.event.inputs.environment }}"
          cloudfront_price_class = "${{ secrets.TF_cloudfront_price_class }}"
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VER }}

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions

      - name: Cleanup previous state
        run: rm -rf .terraform

      - name: Terraform Init
        run: terraform init -backend-config=envs/${{ github.event.inputs.environment }}/backend.tf

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=envs/${{ github.event.inputs.environment }}/terraform.tfvars
        