name: Terraform CI/CD

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

env:
  TF_VER: 1.5.7

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    # Permisos para solicitar tokens OIDC
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        include:
          - env: dev
            branch: refs/heads/develop
            path: envs/dev
          - env: prod
            branch: refs/heads/master
            path: envs/dev

    steps:
      - name: Checkout repo
        if: github.ref == matrix.branch
        uses: actions/checkout@v4

      - name: Setup Terraform
        if: github.ref == matrix.branch
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VER }}

      - name: Configure AWS Credentials via OIDC
        if: github.ref == matrix.branch
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions

      - name: Generate terraform.tfvars
        if: github.ref == matrix.branch
        run: |
          cat > ${{ matrix.path }}/terraform.tfvars <<EOF
          aws_region = "${{ secrets.TF_aws_region }}"
          project_name = "${{ secrets.TF_project_name }}"
          environment = "${{ matrix.env }}"
          cloudfront_price_class = "${{ secrets.TF_cloudfront_price_class }}"
          table_name = "${{ vars.TABLE_NAME }}"
          hash_key = "${{ vars.HASH_KEY }}"
          attributes = "${{ vars.ATTRIBUTES }}"
          ttl_attribute_name = "${{ vars.TTL_ATTRIBUTE_NAME }}"
          ttl_enabled = "${{ vars.TTL_ENABLED }}"
          EOF

      - name: Cleanup previous state
        if: github.ref == matrix.branch
        run: rm -rf .terraform

      - name: Terraform Init
        if: github.ref == matrix.branch
        working-directory: ${{ matrix.path }}
        run: terraform init

      - name: Terraform Plan
        if: github.ref == matrix.branch
        working-directory: ${{ matrix.path }}
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == matrix.branch && github.event_name == 'push'
        working-directory: ${{ matrix.path }}
        run: terraform apply -auto-approve
